doctrine:
    dbal: {
        connections: {
            default: {
                host: '%env(DB_HOST)%',
                port: '%env(DB_PORT)%',
                user: '%env(DB_USER)%',
                password: '%env(DB_PASS)%',
                dbname: '%env(DB_NAME)%'
            }
        }
    }
