pimcore_install:
  parameters:
    database_credentials:
      host: '%env(DB_HOST)%'
      port: '%env(DB_PORT)%'
      user: '%env(DB_USER)%'
      password: '%env(DB_PASS)%'
      dbname: '%env(DB_NAME)%'
