# app/config/installer.yml

pimcore_install:
  parameters:
    database_credentials:
      user:                 root
      password:             root
      dbname:               pimcore

      # env variables can be directly read with the %env() syntax
      # see https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
      host:                 mysql
      port:                 3306